api/urls.py
from django.urls import path, include


v1_patterns = [
    path('auth/', include('auth.urls')),
    path('users/', include('users.urls')),
    path('board/', include('boards.urls')),
    path('activity/', include('activity.urls')),
    path('faqs/', include('FAQs.urls')),
    path('reservations/', include('reservations.urls')),
    path('survey/', include('survey.urls')),
    path('log/', include('logapp.urls')),
    
]

sotonggori = [
    path('', include('sotongapp.urls')),
]

urlpatterns = [
    path('v1/', include(v1_patterns)),
    path('sotong/', include(sotonggori)),
    path('', include('swagger.urls')),
    path('summernote/', include('django_summernote.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('projectadminpage/', admin.site.urls),
    path('api/', include('api.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

survey/urls.py
from django.urls import path, include

from survey.apis import (
    SurveyApi,
    SurveyDetailApi,
    ApplyApi,
    ApplierListApi,
    ApplierDetailApi,
    ApplierFavorApi,
    ApplierCSVApi,
    ApplierFileDownloadApi,
    ApplierSelfCheckApi,
    ApplierDuplicateCheck,
)
from survey.views import *

app_name = "survey"

applier_urlpatterns = [
    path('applier', ApplyApi.as_view(), name='apply'),
    path('applierlist', ApplierListApi.as_view(), name='applierlist'),
    path('applier/<int:applier_id>', ApplierDetailApi.as_view(), name='applier'),
    path('applierfavor/<int:applier_id>', ApplierFavorApi.as_view(), name='applierfavor'),
    
    path('appliercsv', ApplierCSVApi.as_view(), name='appliercsv'),
    path('applierfile/<int:file_id>', ApplierFileDownloadApi.as_view(), name='applierfile'),
    path('applierselfcheck', ApplierSelfCheckApi.as_view(), name='applierselfcheck'),
    path('duplicate', ApplierDuplicateCheck.as_view(), name="check_duplicate"),
    
]

urlpatterns = [
    path('', SurveyApi.as_view(), name='survey'),
    path('<int:survey_id>', SurveyDetailApi.as_view(), name='surveydetail'),
    path('<int:survey_id>/', include(applier_urlpatterns)),
    
    
    path('applierlist', ApplierListView.as_view(), name="list"),
    path('applierdetail/<int:pk>', ApplierDetail, name="detail"),
    path('applierdetail/<int:pk>/finalpick', ApplierFinalPick, name="finalpick"),
]

survey/models.py
import datetime
from uuid import uuid4

from django.db import models
from django.conf import settings



class Survey(models.Model):
    title = models.CharField(max_length=128, null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    
    created_date = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, related_name="survey")
    
    class Meta:
        verbose_name = '지원/설문'
        verbose_name_plural = '지원/설문'
        ordering = ['-start_date', ]
    
    def __str__(self):
        return self.title
    
    def has_permission(self, user):
        return True if self.creator == user else False


class Question(models.Model):
    content = models.TextField(default="", null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    order = models.PositiveIntegerField(null=True, blank=True)
    is_multichoice = models.BooleanField(default=False)
    required = models.BooleanField(default=False)
    can_duplicate = models.BooleanField(default=False)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name="question")
    
    def __str__(self):
        return self.content


class SubQuestion(models.Model):
    sub_content = models.CharField(max_length=128, null=True, blank=True)
    can_select = models.BooleanField(default=False)
    top_question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="sub_question")
    
    def __str__(self):
        return self.sub_content
    
    
class Applier(models.Model):
    name = models.CharField(max_length=64, null=True, blank=True)
    birth = models.CharField(max_length=32, null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    univ = models.CharField(max_length=32, null=True, blank=True)
    is_applied = models.BooleanField("지원 여부", default=False)
    first_picked = models.BooleanField("1차 선발 여부", default=False)
    finaly_picked = models.BooleanField("최종 선발 여부", default=False)
    is_favor = models.BooleanField("관심 지원자", default=False)
    
    apply_date = models.DateTimeField(auto_now_add=True)
    
    GENDER_CHOICE = (
        ("M", "남자"),
        ("F", "여자")
    )
    gender = models.CharField(max_length=8, choices=GENDER_CHOICE)
    
    survey = models.ForeignKey(Survey, null=True, on_delete=models.SET_NULL, related_name="applier")
    
    class Meta:
        verbose_name = '지원자'
        verbose_name_plural = verbose_name
        ordering = ['-apply_date']
    
    def __str__(self):
        return self.name


class Comment(models.Model):
    comment = models.TextField(max_length=2000, default='')
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    applier = models.ManyToManyField(Applier, related_name='comment')
    
    def __str__(self):
        return self.comment
    
    class Meta:
        verbose_name = '지원자'
        verbose_name_plural = verbose_name


class Answer(models.Model):
    answer = models.TextField(default="", null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answer")
    applier = models.ForeignKey(Applier, on_delete=models.CASCADE, related_name="answer")
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name="answer")
    
    def __str__(self):
        return self.answer


def get_file_path(instance, filename):
    ymd_path = datetime.datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return '/'.join(['upload_file_apply/', ymd_path, uuid_name])


class ApplyFile(models.Model):
    apply_file = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=128, null=True, verbose_name='첨부파일명')
    
    applier = models.ForeignKey(Applier, on_delete=models.CASCADE, related_name="applyfile")
    
    class Meta:
        verbose_name = '지원서 첨부파일'
        verbose_name_plural = '지원서 첨부파일'
    
    def __str__(self):
        return self.filename

templates/applierdetail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ appplier.name }}</title>
    <style>
        input:active { 
            position: relative; top:2px; 
        }

    </style>
</head>
<body>
    <div style="text-align: center; width: 50%; line-height: calc(1ex/0.3); margin: 0 auto">
        <hr>
        <h1>{{ survey.title }}</h1>
        <hr>
        <h2>{{ applier.name }}</h2>
        <h4>{{ applier.birth }}</h4>
        <h4>{{ applier.univ }}</h4>
        <form action="{% url 'survey:finalpick' applier.pk %}" method="POST">
            {% csrf_token %}
            {% if applier.finaly_picked %}
                <input style="background-color: tomato; color: white;
                            border: solid 2px tomato; border-radius: 8px;"
                             type="submit" value="합격 취소">
            {% else %}
                <input style="background-color: forestgreen; color: white;
                            border: solid 2px forestgreen; border-radius: 8px;"
                            type="submit" value="최종 선발 하기">
            {% endif %}
        </form>
        <br>
        
        {% for qa in qalist %}
            <hr>
            <h4>
                {{ qa.q }}
            </h4>
            <h5>
                {{ qa.qd }}
            </h5>
            <div style="text-align: left;">
                {{ qa.answer }}
            </div>
            <hr>
        {% endfor %}
        
        
        {% for f in files %}
            <div>
                <a href="{{ f.url }}">{{ f.name }}</a>
            </div>
        {% endfor %}
    </div>
    <br>
    <div>
    </div>
</body>
</html>

templates/applierlist.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>지원자리스트</title>
    <style>
        table {
          width: 60%;
          border: 1px solid #444444;
          border-collapse: collapse;
        }
        th, td {
          border-bottom: 1px solid #444444;
          padding: 5px;
        }
      </style>
</head>
<body>
    <div style="text-align: center; line-height: calc(1ex/0.3); margin: 0 auto">
        <div style="margin-bottom: 2rem; margin-top: 2rem;">
            <form id="searchForm" method="GET" action="{% url 'survey:list' %}">
                <input type="text" id="kw" name="kw" placeholder="name/univ" value="{{ kw|default_if_none:'' }}">
                <input type="text" id="pw" name="pw" placeholder="password" value="{{ pw|default_if_none:'' }}">
                <input type="submit" value="Search by name">
            </form>
        </div>
        <div style="text-align: right;">{{ applier_list.count }} 지원자</div>
        {% if applier_list %}
        <div>
            <table style="line-height: calc(1ex/0.3); border: 1px solid; border-collapse: collapse; margin: 0 auto">
                <tr> <th>이름</th> <th>생년월일</th> <th>학교</th> <th>전화번호</th> <th></th> </tr>
                {% for applier in applier_list %}
                <tr>
                    <td>{{ applier.name }}</td>
                    <td>{{ applier.birth }}</td>
                    <td>{{ applier.univ }}</td>
                    <td>{{ applier.phone }}</td>
                    <td>
                        <form action="{% url 'survey:detail' applier.pk %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="보기">
                        </form>
                    </a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% else %}
            <div style="text-align: center">
                <h1>No appliers</h1>
            </div>
        {% endif %}
    </div>
</body>
</html>

templates/recovery_email.html
<!DOCTYPE html>
<html>
<body>
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">
                        비밀번호 찾기 인증번호 발송
                    </h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;">
                            [PROJECT:HOME] PROJECT 홈페이지 비밀번호찾기 인증번호입니다.
                            <br>아래 인증번호를 인증번호 입력란에 입력해주세요.
                        </p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;">
                        <p style="font-size: 18px; font-weight: bold;">
                            {{ auth_string|safe }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>